### ISSUE TITLE
[BUG] Cannot unzip poing-godot-admob-ios-v4.3.zip

### ISSUE THREAD

**Issue by owlnewworlds** [poingstudios/godot-admob-ios#106]
### Godot version

4.3 RC3

### Plugin version

v3.1.1

### Phone information

N/A

### Issue description

Using Godot 4.3, the downloaded plugin zip file can't be unzipped. Maybe it's because Godot 4.3 isn't compatible yet with your plugin? (It looks like it's support until 4.2.2).

Could you make a release compatible with Godot 4.3, please? Currently, 4.3 is in Release Candidate 3 and all their issues are fixed so the stable version should be released soon. Even though, it would be great to have a compatible 4.3 plugin file.

Thank you! <3

### Steps to reproduce

N/A

**Comment by MarcosFGS-CDS** [comment]
@owlnewworlds I am not sure if this applies to iOS but I just made it work on Android using the 4.2.2 export, just downloaded it from the releases available in the in the repo and manually put it in place, no issues so far.

**Comment by gumaciel** [comment]
Hi, the stable release of Godot 4.3 is coming soon. Please wait a few days, as it might be released shortly.

Until then, you should be able to use 4.2.x stable without issue in 4.3 as @MarcosFGS-CDS said

**Comment by owlnewworlds** [comment]
Godot 4.3 is out since a few days now ^^

Can you tell me if there's a release coming soon for the plugin compatible with Godot 4.3 or if it's worth it to use the 4.2.2 compatible release ? Thank you <3

**Comment by owlnewworlds** [comment]
Sorry to add a comment here but I'm looking for help since I can't make my iOS app to run on my iOS device. I followed several times this video (https://www.youtube.com/watch?v=WpVGn7ZasKM) and the documentation and though the app is building successfully, it can't be run on the iOS device. I get the following error message:

_The item at nokoma.app is not a valid bundle.
Domain: com.apple.dt.CoreDeviceError
Code: 3000
Failure Reason: The path to the provided bundle's main executable could not be determined.
Recovery Suggestion: Ensure that your bundle's Info.plist contains a value for the key CFBundleExecutable._

Does that ring a bell to someone?

**Comment by gumaciel** [comment]
Hey, the official version of Godot 4.3 is out.

@owlnewworlds are you still having issues managing to work on iOS?

**Comment by gumaciel** [comment]
Closing this issue since the original problem seems to be solved.

If you are still having any problem, please open a new issue
