### ISSUE TITLE
[BUG] Project fails to export with error "symbol(s) not found for architecture arm64"

### ISSUE THREAD

**Issue by enrikqose** [poingstudios/godot-admob-ios#107]
### Godot version

4.3 stable

### Plugin version

v3.1.1

### Phone information

N/A

### Issue description

> ld: warning: Could not find or use auto-linked framework 'AudioUnit': framework 'AudioUnit' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'UserMessagingPlatform': framework 'UserMessagingPlatform' not found
Undefined symbols for architecture arm64:
  "_GADAdSizeFromCGSize", referenced from:
      +[GodotDictionaryToObject convertDictionaryToGADAdSize:] in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      PoingGodotAdMobAdSize::getCurrentOrientationAnchoredAdaptiveBannerAdSize(int) in poing-godot-admob-ads.a[arm64][3](PoingGodotAdMobAdSize.o)
  "_GADErrorUserInfoKeyResponseInfo", referenced from:
      +[ObjectToGodotDictionary convertNSErrorToDictionaryAsLoadAdError:] in poing-godot-admob-ads.a[arm64][19](ObjectToGodotDictionary.o)
  "_GADLandscapeAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      PoingGodotAdMobAdSize::getLandscapeAnchoredAdaptiveBannerAdSize(int) in poing-godot-admob-ads.a[arm64][3](PoingGodotAdMobAdSize.o)
  "_GADPortraitAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:
      PoingGodotAdMobAdSize::getPortraitAnchoredAdaptiveBannerAdSize(int) in poing-godot-admob-ads.a[arm64][3](PoingGodotAdMobAdSize.o)
  "_GADSimulatorID", referenced from:
      PoingGodotAdMob::initialize() in poing-godot-admob-ads.a[arm64][2](PoingGodotAdMob.o)
  "_OBJC_CLASS_$_GADBannerView", referenced from:
       in poing-godot-admob-ads.a[arm64][12](BannerAd.o)
  "_OBJC_CLASS_$_GADExtras", referenced from:
       in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_OBJC_CLASS_$_GADInterstitialAd", referenced from:
       in poing-godot-admob-ads.a[arm64][13](InterstitialAd.o)
  "_OBJC_CLASS_$_GADMobileAds", referenced from:
       in poing-godot-admob-ads.a[arm64][2](PoingGodotAdMob.o)
  "_OBJC_CLASS_$_GADRequest", referenced from:
       in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_OBJC_CLASS_$_GADRewardedAd", referenced from:
       in poing-godot-admob-ads.a[arm64][14](RewardedAd.o)
  "_OBJC_CLASS_$_GADRewardedInterstitialAd", referenced from:
       in poing-godot-admob-ads.a[arm64][15](RewardedInterstitialAd.o)
  "_OBJC_CLASS_$_GADServerSideVerificationOptions", referenced from:
       in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_OBJC_CLASS_$_UMPConsentForm", referenced from:
       in poing-godot-admob-ads.a[arm64][10](PoingGodotAdMobUserMessagingPlatform.o)
  "_OBJC_CLASS_$_UMPConsentInformation", referenced from:
       in poing-godot-admob-ads.a[arm64][5](PoingGodotAdMobConsentInformation.o)
  "_OBJC_CLASS_$_UMPDebugSettings", referenced from:
       in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_OBJC_CLASS_$_UMPRequestParameters", referenced from:
       in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_kGADAdSizeSmartBannerLandscape", referenced from:
      PoingGodotAdMobAdSize::getSmartBannerAdSize() in poing-godot-admob-ads.a[arm64][3](PoingGodotAdMobAdSize.o)
      +[GodotDictionaryToObject convertDictionaryToGADAdSize:] in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
  "_kGADAdSizeSmartBannerPortrait", referenced from:
      PoingGodotAdMobAdSize::getSmartBannerAdSize() in poing-godot-admob-ads.a[arm64][3](PoingGodotAdMobAdSize.o)
      +[GodotDictionaryToObject convertDictionaryToGADAdSize:] in poing-godot-admob-ads.a[arm64][18](GodotDictionaryToObject.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce

N/A

**Comment by enrikqose** [comment]
Was installing this by going through readme but after also watching the video it seems this is the expected behaviour.

**Comment by gumaciel** [comment]
Hi, this plugin should work on ARM64, did you solve your issue?

**Comment by enrikqose** [comment]
@gumaciel hi, yes it's working. I didn't watch the video first where it was shown that an error during export was fine because godot doesn't support cocoapods. I was installing the plugin only by going through the steps on readme file and thought it was a fatal error and I couldn't go to the next step. I guess it would be good to add it on the readme than this specific error during export is fine.
