### ISSUE TITLE
Crash on iOS when application is terminating

### ISSUE THREAD

**Issue by abcjjy** [poingstudios/godot-admob-ios#78]
### Godot version

Godot v4.2.rc1

### Plugin version

v3.0.6

### Phone information

iOS 15/16

### Issue description

Crash report from App Store. 10% of the users are impacted.

<img width="720" alt="图片" src="https://github.com/Poing-Studios/godot-admob-ios/assets/1791493/2fa8c322-21b6-48d5-bd9c-57cc70680fd3">

### Steps to reproduce

I don't know how to simulate app termiation event.

**Comment by gumaciel** [comment]
Hi @abcjjy according to the log you've sent, I can't say with certainty that the cause of the application termination is due to our plugin. 

Do you have more information? Can you try to verify if this bug also happens without our plugin enabled?

**Comment by gumaciel** [comment]
@abcjjy does this crash still happen? Can you try to verify if this bug also happens without our plugin enabled?

**Comment by abcjjy** [comment]
This issue only appears in xcode crash log. I haven't found a way to reproduce it yet.

**Comment by gumaciel** [comment]
Hi @abcjjy this bug still reproduce on new Plugin/Godot versions?

**Comment by abcjjy** [comment]
No, it disappears
